# Generated by Django 4.1.4 on 2023-02-02 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_picture', models.ImageField(blank=True, null=True, upload_to='index_picture')),
            ],
        ),
    ]
