# Generated by Django 4.1.4 on 2023-02-02 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageindex',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
